"""empty message

Revision ID: 3a8976117c26
Revises: a15292ec87ca
Create Date: 2017-05-20 15:11:39.193013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8976117c26'
down_revision = 'a15292ec87ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'is_photo_report_attached')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('is_photo_report_attached', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
