"""empty message

Revision ID: a15292ec87ca
Revises: 
Create Date: 2017-05-19 15:21:37.934247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15292ec87ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Engineers',
    sa.Column('id_engineer', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_engineer')
    )
    op.create_table('Tasks',
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_engineer', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('task_description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_engineer'], ['Engineers.id_engineer'], ),
    sa.PrimaryKeyConstraint('id_task')
    )
    op.create_table('Reports',
    sa.Column('id_report', sa.Integer(), nullable=False),
    sa.Column('id_task', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_task'], ['Tasks.id_task'], ),
    sa.PrimaryKeyConstraint('id_report')
    )
    op.create_table('Photos',
    sa.Column('id_photo', sa.Integer(), nullable=False),
    sa.Column('id_report', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_report'], ['Reports.id_report'], ),
    sa.PrimaryKeyConstraint('id_photo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Photos')
    op.drop_table('Reports')
    op.drop_table('Tasks')
    op.drop_table('Engineers')
    # ### end Alembic commands ###
